# This is a dictionary that contains what products are contained in each bundle
product_quant = {
    'HA1014': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 1.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1018': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 1.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1107': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1107NB': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1114': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1115': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1116': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 6.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1123': {'Sons Biotin': 1.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1124': {'Sons Biotin': 3.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 1.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1137': {'Sons Biotin': 3.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1138': {'Sons Biotin': 6.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1141': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 1.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1142': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 2.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1165': {'Sons Biotin': 3.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1170': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1171': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 1.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1210': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0},
    'HA1211': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 1.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0},
    'HA1212': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0},
    'HA1213': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 1.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0},
    'HA1214': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 1.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1215': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 3.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1216': {'Sons Biotin': 1.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 1.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0},
    'HA1217': {'Sons Biotin': 3.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 1.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0},
    'HA1218': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 1.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1219': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 3.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1226': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 1.0,
    'Sons Derma roller': 0.0},
    'HA1227': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 3.0,
    'Sons Derma roller': 0.0},
    'HA1229': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 3.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1230': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 6.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1232': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 1.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 1.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1233': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 3.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 3.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1242': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 3.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1243': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 6.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1245': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 1.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1246': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 3.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1247': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 6.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1249': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 1.0,
    'Sons Conditioner': 1.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1250': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 3.0,
    'Sons Conditioner': 3.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'HA1253': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 6.0,
    'Sons Conditioner': 6.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 0.0},
    'MD1001': {'Sons Biotin': 0.0,
    'Sons 1mg Finasteride': 0.0,
    'Sons Minoxidil 5% 60ml ': 0.0,
    'Sons Minoxidil 5% 180ml ': 0.0,
    'Sons Shampoo ': 0.0,
    'Sons Conditioner': 0.0,
    'Sons Hair Growth Complex': 0.0,
    'Sons Thickening Clay': 0.0,
    'Grey Bar': 0.0,
    'Keto Shampoo': 0.0,
    'Sons Derma roller': 1.0}
}